---
abstract: 'Build browsable HTML documentation for your app'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  Module::Build: 0.35
  Test::File: 0
  Test::MockModule: 0.05
  Test::More: 0.88
  Test::XPath: 0.12
configure_requires:
  Module::Build: 0.35
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Site
provides:
  Pod::Site:
    file: lib/Pod/Site.pm
    version: 0.52
  Pod::Site::Search:
    file: lib/Pod/Site.pm
  Pod::Site::XHTML:
    file: lib/Pod/Site.pm
recommends:
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
requires:
  File::Basename: 0
  File::Copy: 0
  File::Path: 2.07
  File::Spec: 0
  Getopt::Long: 0
  HTML::Entities: 0
  Module::Build: 0.34
  Object::Tiny: 0
  Pod::Simple: 3.12
  Pod::Usage: 0
  perl: 5.006002
resources:
  bugtracker: http://github.com/theory/pod-site/issues/
  homepage: http://search.cpan.org/dist/Pod-Site/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/pod-site/tree/
version: 0.52
